export const GET_PETS_PERSON_SUCCESS = "GET_PETS_PERSON_SUCCESS";
export const GET_PETS_PERSON_ERROR = "GET_PETS_PERSON_ERROR";
export const POST_PET_SUCCESS = "POST_PET_SUCCESS";
export const POST_PET_ERROR = "POST_PET_ERROR";